// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUM77prDaz0flPyWuRgLWoUOMDTI0Gr0A',
    appId: '1:71474238035:web:47b8a30317f4709c7a2ca6',
    messagingSenderId: '71474238035',
    projectId: 'kagi-bus',
    authDomain: 'kagi-bus.firebaseapp.com',
    storageBucket: 'kagi-bus.firebasestorage.app',
    measurementId: 'G-P4LPHVKC49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXeRV9V7mHb94V9UEZWgx18fYZIEvqJM',
    appId: '1:71474238035:android:c8b3e30b78585ce37a2ca6',
    messagingSenderId: '71474238035',
    projectId: 'kagi-bus',
    storageBucket: 'kagi-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-PC0aOprMOYlSH18ifuQlK7Yhd6L7Bc',
    appId: '1:71474238035:ios:da3c96b9b39da9927a2ca6',
    messagingSenderId: '71474238035',
    projectId: 'kagi-bus',
    storageBucket: 'kagi-bus.firebasestorage.app',
    iosBundleId: 'com.myu-mikazuki.kagibus',
  );
}
